from PyQt5 import QtCore
from PyQt5.QtWidgets import QWidget, QVBoxLayout, QLabel, QHBoxLayout, QListWidget, QPushButton, QFrame, \
    QTableWidgetItem, QTableWidget, QSizePolicy, QSpacerItem, QDateEdit, QLineEdit, QComboBox, QGridLayout


class OPSettings(QWidget):

    def __init__(self):
        super().__init__()
        self.verticalLayout_13 = QVBoxLayout(self)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.op_settings_title = QLabel(self)
        self.op_settings_title.setObjectName("op_settings_title")
        self.verticalLayout_13.addWidget(self.op_settings_title)


        # This section is responsible for adding the Lists for add and drop
        self.top_group = QHBoxLayout()
        self.top_group.setObjectName("top_group")
        self.source_list = QListWidget(self)
        self.source_list.setObjectName("source_list")
        self.top_group.addWidget(self.source_list)

        self.top_group_buttons = QVBoxLayout()
        self.top_group_buttons.setObjectName("top_group_buttons")
        self.verticalLayout_2 = QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.move_selected = QPushButton(self)
        self.move_selected.setObjectName("move_selected")
        self.verticalLayout_2.addWidget(self.move_selected)
        self.move_all = QPushButton(self)
        self.move_all.setObjectName("move_all")
        self.verticalLayout_2.addWidget(self.move_all)
        self.top_group_buttons.addLayout(self.verticalLayout_2)
        self.verticalLayout = QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.return_selected = QPushButton(self)
        self.return_selected.setObjectName("return_selected")
        self.verticalLayout.addWidget(self.return_selected)
        self.return_all = QPushButton(self)
        self.return_all.setObjectName("return_all")
        self.verticalLayout.addWidget(self.return_all)
        self.top_group_buttons.addLayout(self.verticalLayout)
        self.top_group.addLayout(self.top_group_buttons)

        self.destination_list = QListWidget(self)
        self.destination_list.setObjectName("destination_list")
        self.top_group.addWidget(self.destination_list)
        self.verticalLayout_13.addLayout(self.top_group)


        # This is the middle section of the form
        self.middle_group = QFrame(self)
        # self.middle_group.setStyleSheet("#frame{\n"
        #                                 "    background: white;\n"
        #                                 "    border: 1px solid black;\n"
        #                                 "    padding: 10px;\n"
        #                                 "    margin-top: 10px;\n"
        #                                 "    margin-bottom: 10px;\n"
        #                                 "}")

        self.middle_group.setFrameShape(QFrame.StyledPanel)
        self.middle_group.setFrameShadow(QFrame.Raised)
        self.middle_group.setObjectName("middle_group")
        self.gridLayout = QGridLayout(self.middle_group)
        self.gridLayout.setObjectName("gridLayout")

        # The buttons area
        self.verticalLayout_12 = QVBoxLayout()
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.op_save = QPushButton(self.middle_group)
        self.op_save.setObjectName("op_save")
        self.verticalLayout_12.addWidget(self.op_save)
        self.op_delete = QPushButton(self.middle_group)
        self.op_delete.setObjectName("op_delete")
        self.verticalLayout_12.addWidget(self.op_delete)
        self.op_clear = QPushButton(self.middle_group)
        self.op_clear.setObjectName("op_clear")
        self.verticalLayout_12.addWidget(self.op_clear)
        self.op_close = QPushButton(self.middle_group)
        self.op_close.setObjectName("op_close")
        self.verticalLayout_12.addWidget(self.op_close)

        self.gridLayout.addLayout(self.verticalLayout_12, 0, 2, 1, 1)
        self.horizontalLayout_2 = QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_10 = QVBoxLayout()
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.verticalLayout_4 = QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.op_category_label = QLabel(self.middle_group)
        self.op_category_label.setObjectName("op_category_label")
        self.verticalLayout_4.addWidget(self.op_category_label)
        self.op_category = QComboBox(self.middle_group)
        self.op_category.setMaximumSize(QtCore.QSize(192, 16777215))
        self.op_category.setObjectName("op_category")
        self.verticalLayout_4.addWidget(self.op_category)
        self.verticalLayout_10.addLayout(self.verticalLayout_4)
        self.verticalLayout_6 = QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.op_validity_days_label = QLabel(self.middle_group)
        self.op_validity_days_label.setObjectName("op_validity_days_label")
        self.verticalLayout_6.addWidget(self.op_validity_days_label)
        self.op_validity_days = QLineEdit(self.middle_group)
        self.op_validity_days.setMaximumSize(QtCore.QSize(185, 16777215))
        self.op_validity_days.setObjectName("op_validity_days")
        self.verticalLayout_6.addWidget(self.op_validity_days)
        self.verticalLayout_10.addLayout(self.verticalLayout_6)
        self.verticalLayout_8 = QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.op_max_visit_label = QLabel(self.middle_group)
        self.op_max_visit_label.setObjectName("op_max_visit_label")
        self.verticalLayout_8.addWidget(self.op_max_visit_label)
        self.op_max_visit = QLineEdit(self.middle_group)
        self.op_max_visit.setMaximumSize(QtCore.QSize(192, 16777215))
        self.op_max_visit.setObjectName("op_max_visit")
        self.verticalLayout_8.addWidget(self.op_max_visit)
        self.verticalLayout_10.addLayout(self.verticalLayout_8)
        self.horizontalLayout_2.addLayout(self.verticalLayout_10)

        spacerItem = QSpacerItem(20, 20, QSizePolicy.Minimum, QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.verticalLayout_11 = QVBoxLayout()
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.verticalLayout_5 = QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.op_renewal_label = QLabel(self.middle_group)
        self.op_renewal_label.setObjectName("op_renewal_label")
        self.verticalLayout_5.addWidget(self.op_renewal_label)
        self.op_renewal = QComboBox(self.middle_group)
        self.op_renewal.setMaximumSize(QtCore.QSize(191, 16777215))
        self.op_renewal.setObjectName("op_renewal")
        self.verticalLayout_5.addWidget(self.op_renewal)
        self.verticalLayout_11.addLayout(self.verticalLayout_5)
        self.verticalLayout_7 = QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.op_perday_visit_label = QLabel(self.middle_group)
        self.op_perday_visit_label.setObjectName("op_perday_visit_label")
        self.verticalLayout_7.addWidget(self.op_perday_visit_label)
        self.op_perday_visit = QLineEdit(self.middle_group)
        self.op_perday_visit.setMaximumSize(QtCore.QSize(191, 16777215))
        self.op_perday_visit.setObjectName("op_perday_visit")
        self.verticalLayout_7.addWidget(self.op_perday_visit)
        self.verticalLayout_11.addLayout(self.verticalLayout_7)
        self.verticalLayout_9 = QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.date_label = QLabel(self.middle_group)
        self.date_label.setObjectName("date_label")
        self.verticalLayout_9.addWidget(self.date_label)
        self.dateEdit = QDateEdit(self.middle_group)
        self.dateEdit.setMaximumSize(QtCore.QSize(191, 16777215))
        self.dateEdit.setObjectName("dateEdit")
        self.verticalLayout_9.addWidget(self.dateEdit)
        self.verticalLayout_11.addLayout(self.verticalLayout_9)
        self.horizontalLayout_2.addLayout(self.verticalLayout_11)
        self.gridLayout.addLayout(self.horizontalLayout_2, 0, 0, 1, 1)
        spacerItem1 = QSpacerItem(280, 20, QSizePolicy.Minimum, QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 0, 1, 1, 1)
        self.verticalLayout_13.addWidget(self.middle_group)

        # The table section
        self.op_table = QTableWidget(self)
        self.op_table.setObjectName("op_table")
        self.op_table.setColumnCount(7)
        self.op_table.setRowCount(4)
        item = QTableWidgetItem()
        self.op_table.setVerticalHeaderItem(0, item)
        item = QTableWidgetItem()
        self.op_table.setVerticalHeaderItem(1, item)
        item = QTableWidgetItem()
        self.op_table.setVerticalHeaderItem(2, item)
        item = QTableWidgetItem()
        self.op_table.setVerticalHeaderItem(3, item)
        item = QTableWidgetItem()
        self.op_table.setHorizontalHeaderItem(0, item)
        item = QTableWidgetItem()
        self.op_table.setHorizontalHeaderItem(1, item)
        item = QTableWidgetItem()
        self.op_table.setHorizontalHeaderItem(2, item)
        item = QTableWidgetItem()
        self.op_table.setHorizontalHeaderItem(3, item)
        item = QTableWidgetItem()
        self.op_table.setHorizontalHeaderItem(4, item)
        item = QTableWidgetItem()
        self.op_table.setHorizontalHeaderItem(5, item)
        item = QTableWidgetItem()
        self.op_table.setHorizontalHeaderItem(6, item)
        item = QTableWidgetItem()
        self.op_table.setItem(0, 0, item)
        item = QTableWidgetItem()
        self.op_table.setItem(0, 1, item)
        item = QTableWidgetItem()
        self.op_table.setItem(0, 2, item)
        item = QTableWidgetItem()
        self.op_table.setItem(0, 3, item)
        item = QTableWidgetItem()
        self.op_table.setItem(0, 4, item)
        item = QTableWidgetItem()
        self.op_table.setItem(0, 5, item)
        item = QTableWidgetItem()
        self.op_table.setItem(0, 6, item)
        item = QTableWidgetItem()
        self.op_table.setItem(1, 0, item)
        item = QTableWidgetItem()
        self.op_table.setItem(1, 1, item)
        item = QTableWidgetItem()
        self.op_table.setItem(1, 2, item)
        item = QTableWidgetItem()
        self.op_table.setItem(1, 3, item)
        item = QTableWidgetItem()
        self.op_table.setItem(1, 4, item)
        item = QTableWidgetItem()
        self.op_table.setItem(1, 5, item)
        item = QTableWidgetItem()
        self.op_table.setItem(1, 6, item)
        item = QTableWidgetItem()
        self.op_table.setItem(2, 0, item)
        item = QTableWidgetItem()
        self.op_table.setItem(2, 1, item)
        item = QTableWidgetItem()
        self.op_table.setItem(2, 2, item)
        item = QTableWidgetItem()
        self.op_table.setItem(2, 3, item)
        item = QTableWidgetItem()
        self.op_table.setItem(2, 4, item)
        item = QTableWidgetItem()
        self.op_table.setItem(2, 5, item)
        item = QTableWidgetItem()
        self.op_table.setItem(2, 6, item)
        item = QTableWidgetItem()
        self.op_table.setItem(3, 0, item)
        item = QTableWidgetItem()
        self.op_table.setItem(3, 1, item)
        item = QTableWidgetItem()
        self.op_table.setItem(3, 2, item)
        item = QTableWidgetItem()
        self.op_table.setItem(3, 3, item)
        item = QTableWidgetItem()
        self.op_table.setItem(3, 4, item)
        item = QTableWidgetItem()
        self.op_table.setItem(3, 5, item)
        item = QTableWidgetItem()
        self.op_table.setItem(3, 6, item)
        self.verticalLayout_13.addWidget(self.op_table)

        self.retranslateUi()


    def retranslateUi(self):
        # _translate = QtCore.QCoreApplication.translate
        # Form.setWindowTitle( "Form")
        self.op_settings_title.setText( "Out Patient Settings Master")
        self.move_selected.setText( "PushButton")
        self.move_all.setText( "PushButton")
        self.return_selected.setText( "PushButton")
        self.return_all.setText( "PushButton")
        self.op_save.setText( "Save")
        self.op_delete.setText( "Delete")
        self.op_clear.setText( "Clear")
        self.op_close.setText( "Close")
        self.op_category_label.setText( "OP. Category")
        self.op_validity_days_label.setText( "OP. Validity Days")
        self.op_max_visit_label.setText( "OP. Max Visit No.")
        self.op_renewal_label.setText( "OP. Renewal")
        self.op_perday_visit_label.setText( "OP. Per Day Visit No.")
        self.date_label.setText( "Date")

        item = self.op_table.verticalHeaderItem(0)
        item.setText( "1")
        item = self.op_table.verticalHeaderItem(1)
        item.setText( "2")
        item = self.op_table.verticalHeaderItem(2)
        item.setText( "3")
        item = self.op_table.verticalHeaderItem(3)
        item.setText( "4")
        item = self.op_table.horizontalHeaderItem(0)
        item.setText( "Name")
        item = self.op_table.horizontalHeaderItem(1)
        item.setText( "OP.Category")
        item = self.op_table.horizontalHeaderItem(2)
        item.setText( "Address")
        item = self.op_table.horizontalHeaderItem(3)
        item.setText( "Renewal")
        item = self.op_table.horizontalHeaderItem(4)
        item.setText( "Validity")
        item = self.op_table.horizontalHeaderItem(5)
        item.setText( "Max Visit")
        item = self.op_table.horizontalHeaderItem(6)
        item.setText( "Per Day")
        # __sortingEnabled = self.op_table.isSortingEnabled()
        # self.op_table.setSortingEnabled(False)

        item = self.op_table.item(0, 0)
        item.setText( "Kemi")
        item = self.op_table.item(0, 1)
        item.setText( "General")
        item = self.op_table.item(0, 2)
        item.setText( "Isokan ext. Akobo Ojuring")
        item = self.op_table.item(0, 3)
        item.setText( "Y")
        item = self.op_table.item(0, 4)
        item.setText( "2")
        item = self.op_table.item(0, 5)
        item.setText( "4")
        item = self.op_table.item(0, 6)
        item.setText( "3")
        item = self.op_table.item(1, 0)
        item.setText( "Oyinda")
        item = self.op_table.item(1, 1)
        item.setText( "Special")
        item = self.op_table.item(1, 2)
        item.setText( "Olorundas")
        item = self.op_table.item(1, 3)
        item.setText( "Y")
        item = self.op_table.item(1, 4)
        item.setText( "2")
        item = self.op_table.item(1, 5)
        item.setText( "10")
        item = self.op_table.item(1, 6)
        item.setText( "4")
        item = self.op_table.item(2, 0)
        item.setText( "Ayo")
        item = self.op_table.item(2, 1)
        item.setText( "General")
        item = self.op_table.item(2, 2)
        item.setText( "Akobo")
        item = self.op_table.item(2, 3)
        item.setText( "Y")
        item = self.op_table.item(2, 4)
        item.setText( "7")
        item = self.op_table.item(2, 5)
        item.setText( "3")
        item = self.op_table.item(2, 6)
        item.setText( "1")
        item = self.op_table.item(3, 0)
        item.setText( "Wale")
        item = self.op_table.item(3, 1)
        item.setText( "Special")
        item = self.op_table.item(3, 2)
        item.setText( "America")
        item = self.op_table.item(3, 3)
        item.setText( "Y")
        item = self.op_table.item(3, 4)
        item.setText( "10")
        item = self.op_table.item(3, 5)
        item.setText( "30")
        item = self.op_table.item(3, 6)
        item.setText( "30")
        # self.op_table.setSortingEnabled(__sortingEnabled)